---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis
    author: manasa
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6380
...