---
apiVersion: v1
kind: Pod
metadata:
  name: resultapp-pod
  labels:
    name: result-app
    author: manasa
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
...