---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    name: voting-app
    author: manasa
spec:
  replicas: 2
  selector:
    matchLabels:
      name: voting-app
      author: manasa
  template:
    metadata:
      labels:
        name: voting-app
        author: manasa
    spec:
      containers:
        - name: voting-app-pod
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
...
