---
apiVersion: v1
kind: Pod
metadata:
  name: votingapp-pod
  labels:
    name: voting-app
    author: manasa
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80
...