---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app
    author: manasa
spec:
  replicas:1
  selector:
    matchLabels:
      name: worker-app
      author: manasa
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app
        author: manasa
    spec:
      containers:
        - name: worker-app-pod
          image: dockersamples/examplevotingapp_worker
          ports:
            - containerPort: 80
...