---
apiVersion: v1
kind: Pod
metadata:
  name: workerapp-pod
  labels:
    name: worker-app
    author: manasa
spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker
      ports:
        - containerPort: 80

...